# Generated by Django 3.1.6 on 2021-02-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Publicar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('sub_titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('data_criar', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=False)),
                ('destacar', models.BooleanField(default=False)),
                ('temas', models.ManyToManyField(blank=True, null=True, to='app.Tema')),
            ],
        ),
    ]
