# Generated by Django 3.1.6 on 2021-02-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicar',
            name='imagem',
            field=models.ImageField(blank=True, default='/images/placeholder2.png', null=True, upload_to='images'),
        ),
    ]
